version: "3.8"

services:
  taskoo.web:
    build: ./infrastructure/docker/web/
    container_name: taskoo.web
    tty: true
    ports:
      - 3000:3000
      - 6006:6006
      - 9229:9229
    command: >
      bash -c "cd ./web/ && ./scripts/run_dev.sh"
    volumes:
      - ./.vscode:/opt/app/src/.vscode
      - ./.git:/opt/app/src/.git
      - ./.gitignore:/opt/app/src/.gitignore
      - ./web:/opt/app/src/web

  taskoo.firebase:
    build: ./infrastructure/docker/firebase/
    container_name: taskoo.firebase
    tty: true
    ports:
      - 4000:4000
      - 5001:5001
      - 8080:8080
      - 9005:9005
      - 9099:9099
    command: >
      bash -c "./infrastructure/firebase/scripts/run_preprocess.sh"
    volumes:
      - ./.vscode:/opt/app/src/.vscode
      - ./.git:/opt/app/src/.git
      - ./.gitignore:/opt/app/src/.gitignore
      - ./_shared_storage:/opt/app/src/_shared_storage
      - ./infrastructure/firebase:/opt/app/src/infrastructure/firebase
      - ./functions:/opt/app/src/functions
      - ./.firebaserc:/opt/app/src/.firebaserc
      - ./firebase.json:/opt/app/src/firebase.json
