name: Run test

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          check-latest: true

      - uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/web/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: install yarn
        run: npm install -g yarn
      - name: install
        run: yarn
        working-directory: ./web
      - name: build build
        run: yarn build
        working-directory: ./web
      - name: test
        run: yarn test
        working-directory: ./web
