name: Run test

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          check-latest: true

      - uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/web/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-
      # インストール
      - name: install yarn
        run: npm install -g yarn
      - name: install
        run: yarn --frozen-lockfile
        working-directory: ./web

      # テスト
      - name: build build
        run: yarn build
        working-directory: ./web
      - name: test
        run: yarn test
        working-directory: ./web

      # デプロイ
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TASKOO_DAVOUT_V1 }}'
          channelId: live
          projectId: taskoo-davout-v1
