name: Test & Deploy Functions

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  check-diff:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.diff.outputs.diff }}
    steps:
      - uses: actions/checkout@v3
      - name: check existing diff
        id: diff
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            functions/**/*
      - name: display diff
        run: echo ${{ env.GIT_DIFF }}

  test-and-deploy:
    runs-on: ubuntu-latest
    needs: check-diff
    if: needs.check-diff.outputs.diff
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          check-latest: true

      - name: install yarn
        run: npm install -g yarn

      - name: get node_modules cache
        uses: actions/cache@v3
        with:
          path: |
            functions/node_modules
          key: ${{ runner.os }}-functions-node_modules-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - name: yarn install
        run: yarn --frozen-lockfile --prefer-offline
        working-directory: ./functions

      # Cloud Functionのビルド
      - name: build
        run: yarn build
        working-directory: ./functions

      - name: deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project=taskoo-davout-v1
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
