name: Test & Deploy Web

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  check-diff:
    runs-on: ubuntu-latest
    outputs:
      diff: ${{ steps.diff.outputs.diff }}
    steps:
      - uses: actions/checkout@v3
      - name: check existing diff
        id: diff
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            web/**/*
      - name: display diff
        run: echo ${{ env.GIT_DIFF }}

  test-and-deploy:
    runs-on: ubuntu-latest
    needs: check-diff
    if: needs.check-diff.outputs.diff
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          check-latest: true
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          check-latest: true

      - name: get yarn cache
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/web/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - name: install yarn
        run: npm install -g yarn
      - name: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
        working-directory: ./web

      # 環境変数読み込み
      - name: load env
        env:
          BASE64_ENV_PROD: ${{ secrets.BASE64_ENV_PROD }}
        run: echo -n $BASE64_ENV_PROD | base64 --decode > ./web/.env.production.local

      # テスト
      - name: test
        run: yarn test
        working-directory: ./web
      - name: build
        run: yarn build
        working-directory: ./web

      # デプロイ
      - name: export
        run: yarn export
        working-directory: ./web
      - name: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TASKOO_DAVOUT_V1 }}'
          channelId: live
          projectId: taskoo-davout-v1
