name: Test & Deploy Web

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 差分があるかチェック
        id: diff_web
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            web/**/*
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          check-latest: true
        if: steps.diff_web.outputs.diff

      - name: get yarn cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/web/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-
        if: steps.diff_web.outputs.diff

      - name: install yarn
        run: npm install -g yarn
        if: steps.diff_web.outputs.diff
      - name: yarn install
        run: yarn --frozen-lockfile
        working-directory: ./web
        if: steps.diff_web.outputs.diff

      # テスト
      - name: build
        run: yarn build
        working-directory: ./web
        if: steps.diff_web.outputs.diff
      - name: test
        run: yarn test
        working-directory: ./web
        if: steps.diff_web.outputs.diff

      # デプロイ
      - name: export
        run: yarn export
        working-directory: ./web
        if: steps.diff_web.outputs.diff
      - name: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TASKOO_DAVOUT_V1 }}'
          channelId: live
          projectId: taskoo-davout-v1
        if: steps.diff_web.outputs.diff
